/**
 * Auto-generated by `pnpm payload generate:importmap`.
 * This stub is kept committed so the build doesn't fail before first generation.
 * After modifying any field component or admin override, regenerate this file.
 */
export const importMap = {};
